components:
  schemas:
    Echo:
      description: Response model for echo endpoint.
      properties:
        text:
          description: The echo
          examples:
          - HELLO, WORLD!
          minLength: 1
          title: Text
          type: string
      required:
      - text
      title: Echo
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    Health:
      description: 'Represents the health status of a service with optional components
        and failure reasons.


        A health object can have child components, each with its own health status.

        The parent health is automatically computed from its components - it is

        considered UP only if all child components are UP. If any component is DOWN,

        the parent will also be DOWN with a reason listing the failed components.'
      properties:
        components:
          additionalProperties:
            $ref: '#/components/schemas/Health'
          title: Components
          type: object
        reason:
          anyOf:
          - type: string
          - type: 'null'
          title: Reason
        status:
          $ref: '#/components/schemas/_HealthStatus'
      required:
      - status
      title: Health
      type: object
    Utterance:
      description: Model representing a text utterance.
      properties:
        text:
          description: The utterance to echo back
          examples:
          - Hello, world!
          minLength: 1
          title: Text
          type: string
      required:
      - text
      title: Utterance
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
    _HealthStatus:
      enum:
      - UP
      - DOWN
      title: _HealthStatus
      type: string
    _HelloWorldResponse:
      description: Response model for hello-world endpoint.
      properties:
        message:
          description: The hello world message
          examples:
          - Hello, world!
          title: Message
          type: string
      required:
      - message
      title: _HelloWorldResponse
      type: object
info:
  contact:
    email: helmuthva@gmail.com
    name: Helmut Hoffer von Ankershoffen
    url: https://github.com/helmut-hoffer-von-ankershoffen/oe-python-template
  termsOfService: https://oe-python-template.readthedocs.io/en/latest/
  title: OE Python Template
  version: 2.0.0
openapi: 3.1.0
paths:
  /health:
    get:
      description: "Check the health of the system.\n\nThis operation returns the\
        \ health of the system.\nThe status can be either UP or DOWN.\nIf the service\
        \ is healthy, the status will be UP.\nIf the service is unhealthy, the status\
        \ will be DOWN and a reason will be provided.\nThe response will have a 200\
        \ OK status code if the service is healthy,\nand a 500 Internal Server Error\
        \ status code if the service is unhealthy.\n\nReturns:\n    Health: The health\
        \ of the system."
      operationId: health_endpoint_health_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
          description: Successful Response
      summary: Health Endpoint
      tags:
      - system
  /healthz:
    get:
      description: "Check the health of the system.\n\nThis operation returns the\
        \ health of the system.\nThe status can be either UP or DOWN.\nIf the service\
        \ is healthy, the status will be UP.\nIf the service is unhealthy, the status\
        \ will be DOWN and a reason will be provided.\nThe response will have a 200\
        \ OK status code if the service is healthy,\nand a 500 Internal Server Error\
        \ status code if the service is unhealthy.\n\nReturns:\n    Health: The health\
        \ of the system."
      operationId: health_endpoint_healthz_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
          description: Successful Response
      summary: Health Endpoint
      tags:
      - system
  /hello/echo:
    post:
      description: "Echo back the provided utterance.\n\nArgs:\n    request (Utterance):\
        \ The utterance to echo back.\n\nReturns:\n    Echo: The echo.\n\nRaises:\n\
        \    422 Unprocessable Entity: If utterance is not provided or empty."
      operationId: echo_v2_hello_echo_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Utterance'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Echo'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Echo V2
      tags:
      - hello
  /hello/world:
    get:
      description: "Return a hello world message.\n\nReturns:\n    _HelloWorldResponse:\
        \ A response containing the hello world message."
      operationId: hello_world_hello_world_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_HelloWorldResponse'
          description: Successful Response
      summary: Hello World
      tags:
      - hello
